[supervisord]
nodaemon=true
user=root

[program:named]
command=/usr/sbin/named -g -c /etc/bind/named.conf
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:webmin]
command=/usr/share/webmin/miniserv.pl -f /etc/webmin/miniserv.conf
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
